import type { Metadata } from "next";
import "./globals.css";
import SideNav from "./ui/components/sidenav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={"flex flex-col relative w-full h-screen bg-cover bg-[url('/assets/home/background-home-mobile.jpg')] md:bg-[url('/assets/home/background-home-tablet.jpg')]	 lg:bg-[url('/assets/home/background-home-desktop.jpg')]"}
      >
        <div>
          <SideNav/>
        </div>
        <div className="h-full">
          {children}
        </div>
      </body>
    </html>
  );
}
