import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import SideNav from "./ui/components/sidenav";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={"flex flex-col h-screen bg-cover bg-[url('/assets/home/background-home-mobile.jpg')] md:bg-[url('/assets/home/background-home-tablet.jpg')]	 lg:bg-[url('/assets/home/background-home-desktop.jpg')]"}
      >
        <div>
          <SideNav/>
        </div>
        {children}
      </body>
    </html>
  );
}
